server:
  port: 24110

spring:
  application:
    name: publisher
  datasource:
    url: jdbc:h2:mem:publisher;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  discussion:
    base-url: http://localhost:24130
