version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=distcomp-cluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M