spring:
  autoconfigure:
    exclude: []
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: distcomp
    local-datacenter: datacenter1
    schema-action: none
    request:
      timeout: 10s
