server:
  port: 24110

spring:
  application:
    name: publisher

  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  webclient:
    baseUrl: http://localhost:24130/api/v1.0

logging:
  level:
    com.task.publisher: DEBUG