spring:
  application:
    name: l-labs
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: distcomp
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    liquibase-schema: public
    default-schema: distcomp
  sql:
    init:
      mode: never

server:
  port: 24110

