server:
  port: 24130
  servlet:
    context-path: /api/v1.0

spring:
  application:
    name: discussion

    cassandra:
      keyspace-name: distcomp
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: none

logging:
  level:
    root: INFO
    com.task.discussion: DEBUG
